{
  env: 'CartPole-v0',
  policy: 'Mlp',
  reward: 'Identity',
  model_building_parameters: {
    model_name: 'testing_config',
    memory_size: 50000,
    batch_size: 256,
    logger_steps: 150,
    learning_starts: 1000
  },
  timesteps: 10000
}