{
  env: 'CartPole-v0',
  policy: 'Mlp',
  reward: 'Identity',
  model_building_parameters: {
    model_name: 'testing_save_and_reload',
    memory_size: 50000,
    batch_size: 256,
    logger_steps: 150,
    learning_starts: 500
  },
  timesteps: 1000,
  reload: True,
  saved_model: 'DQN1/timesteps_999',
}