{
  run_name: 'debugging_vanilla',
  model: "DDPG",
  environment: "Pendulum-v0",
  logging: True,
  save_model: False,
  
  environment_parameters: {},

  model_parameters: {
    verbose: 0
  },

  learning_parameters: {
    timesteps: 10000
  },

  callback_parameters: {
    save_freq: 2000,
    eval_freq: 250,
    shap_samples: 50,
    test_samples: 10,
    summarize: True,
    num_summaries: 12,
    log_shap_vals: 200
  }


}